[platformio]
default_envs = generic_esp32_demo

[env:generic_esp32_demo]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_build.partitions = huge_app.csv
build_flags =
  -DCORE_DEBUG_LEVEL=0
lib_deps =
  bblanchon/ArduinoJson@^7.1.0
  knolleary/PubSubClient@^2.8
  adafruit/Adafruit GFX Library@^1.11.11
  adafruit/Adafruit ST7735 and ST7789 Library@^1.10.4

; ideaspark ESP32 1.9 inch LCD(Solder PIN), ASIN B0D6QXC813.
; The product behaves like a classic ESP32 DevKit with integrated ST7789 display.
